// @ts-nocheck
export const T = {
  nl: { title:"WK 2026 POULE", subtitle:"USA • CANADA • MEXICO",
    tabs:{ranking:"Ranglijst",matches:"Wedstrijden",matches2:"Wedstrijden 2",results:"Uitslagen",teams:"Teams",competitions:"Alle competities",register:"Inschrijven",register2:"Inschrijven 2",edit:"Mijn team",rules:"Regels",competition:"Competitie",poolPoints:"Puntenbeheer",admin:"Beheer"},
    competitionTab:{
      title:"Competitie",
      intro:"Pools die jij aanmaakt, beheer je hier. Deel de slug zodat vrienden bij dezelfde competitie inschrijven.",
      signInHint:"Log in via Mijn team om een pool aan te maken.",
      goToMyTeam:"Naar Mijn team",
      createPool:"Nieuwe pool",
      slugPh:"slug (bijv. kantoor-2026)",
      namePh:"Weergavenaam",
      seasonPh:"seizoen (optioneel)",
      submitCreate:"Aanmaken",
      yourPools:"Jouw competities",
      noPoolsYet:"Nog geen pools — maak er een hierboven.",
      poolIdLabel:"Pool-id",
      slugLabel:"Slug",
      startsLabel:"Start",
      teamsLabel:"Teams ingeschreven",
      fixturesTitle:"Fixture-koppelingen (API Football id)",
      saveMap:"Opslaan",
      noMappings:"Nog geen wedstrijdregels voor deze pool (worden toegevoegd als de competitie is geseed).",
      manage:"Beheren",
      selected:"Geselecteerd",
      delete:"Verwijderen",
      createFailed:"Aanmaken mislukt",
      deleteFailed:"Verwijderen mislukt",
      fixtureIdPositive:"Fixture-id moet een positief geheel getal zijn.",
      fixtureDup:"Die API fixture-id is al in gebruik in deze pool.",
      mappingFailed:"Koppeling mislukt",
      slugNameRequired:"Slug en naam zijn verplicht.",
      leagueTypeLabel:"Competitietype (API-Football)",
      leagueTypePlaceholder:"— kies type —",
      leagueTypeRequired:"Kies een competitietype.",
      leagueTypeReadonlyHint:"Competitietype kan na aanmaken niet worden gewijzigd.",
      confirmDelTitle:"Competitie verwijderen?",
      confirmDelBody:"Dit verwijdert de pool als de database het toelaat (bestaande teams kunnen verwijderen blokkeren).",
      confirmDelete:"Verwijderen",
      editSection:"Bewerken",
      metadataLabel:"Metadata (JSON)",
      metadataHint:"Optioneel: extra instellingen als geldige JSON.",
      updateFailed:"Opslaan mislukt",
      updated:"Opgeslagen",
      clearStart:"Geen startdatum (wissen)",
      metadataInvalid:"Metadata moet geldige JSON zijn (een object).",
      invitesTitle:"E-mailuitnodigingen",
      invitesHelp:"We sturen een link (configureer Brevo of Resend + PUBLIC_APP_URL in de API). De genodigde logt in met dat e-mailadres en schrijft zich in via Inschrijven.",
      inviteEmailPh:"vriend@voorbeeld.nl",
      sendInvite:"Uitnodiging versturen",
      invitePending:"openstaand",
      inviteAccepted:"geaccepteerd",
      noInvitesYet:"Nog geen uitnodigingen voor deze pool.",
      inviteEmailRequired:"Vul een e-mailadres in.",
      inviteNoEmail:"E-mail niet verstuurd. Kopieer de link; onderaan staat de technische reden (API-server).",
      inviteSendFailed:"Uitnodiging mislukt",
      importFixturesTitle:"Wedstrijden importeren (API-Football)",
      importFixturesHint:"Haal het volledige schema op en sla het op als fixture-koppelingen voor deze pool. Vereist API_FOOTBALL_KEY op de server. Optioneel: league- en seizoens-id (API-Football); anders metadata.api_football in JSON hierboven.",
      importFixturesLeagueLabel:"API league-id",
      importFixturesSeasonLabel:"Seizoen (jaar)",
      importFixturesButton:"Wedstrijden ophalen & opslaan",
      importFixturesBusy:"Bezig met importeren…",
      importFixturesSuccess:"{n} wedstrijden opgeslagen ({total} uit API).",
      importFixturesNone:"Geen rijen geïmporteerd.",
      fetchAllFixtureSquadsButton:"Spelers voor alle wedstrijden ophalen",
      fetchAllFixtureSquadsBusy:"Bezig met starten…",
      fetchAllFixtureSquadsHint:"Start op de server een achtergrondtaak: per wedstrijd max. één API-aanroep, daarna 3 seconden pauze. Al ingelezen teams (zelfde league, seizoen en teamnaam) worden overgeslagen.",
      fetchAllFixtureSquadsStarted:"Selecties worden opgehaald (achtergrond).",
      fetchAllFixtureSquadsFailed:"Ophalen van selecties mislukt",
      fetchAllFixtureSquadsNoMappings:"Geen wedstrijden met een geldige API fixture-id.",
    },
    allCompetitionsTab:{
      title:"Alle competities",
      intro:"Openbare pools, poolstart (inschrijving sluit dan) en wie de pool heeft aangemaakt. Is inschrijven nog open? Ga dan door naar Inschrijven voor die pool.",
      empty:"Geen competities gevonden.",
      openBadge:"Inschrijving open",
      closedBadge:"Gesloten",
      organizer:"Organisator",
      teams:"Teams ingeschreven",
      deadline:"Inschrijving sluit (poolstart)",
      starts:"Poolstart",
      created:"Pool aangemaakt",
      poolId:"Pool-id",
      slugLabel:"Slug",
      metadata:"Metadata",
      registerCta:"Inschrijven voor deze competitie",
      joining:"Bezig met aanmelden…",
      closedHint:"De pool is gestart — inschrijven is gesloten.",
      ownerIdOnly:"Organizer-account",
      platformPool:"Platform / standaard pool",
      joinOwnPoolError:
        "Dit is jouw eigen pool. Je beheert die onder Competitie; je kunt jezelf hier niet als deelnemer aanmelden. Stuur uitnodigingen naar anderen om mee te doen.",
    },
    matches2Tab:{
      selectCompetition:"Competitie",
      noCompetitionsList:"Geen competities beschikbaar.",
      needCompetition:"Kies eerst een competitie (Alle competities of Inschrijven) om het schema te laden.",
      empty:"Nog geen wedstrijdkoppelingen voor deze pool.",
      loadError:"Laden mislukt.",
      noKickoffYet:"Datum nog niet bekend",
      noGroupTeams:"Nog geen groepsfase met teamnamen in de fixture-data.",
      fromMappings:"uit pool-schema",
      competitionScheduleNote:"Tijden volgen de officiële speeltijdzone van deze competitie (niet je profiel-tijdzone).",
      noPoolStartDate:"Deze pool heeft nog geen startdatum — die kan de organisator instellen bij bewerken.",
      viewStatistics:"Bekijk statistieken",
      statsDialogTitle:"Wedstrijdstatistieken",
      statsClose:"Sluiten",
      statsSourceDatabase:"Uit opgeslagen gegevens",
      statsSourceApi:"Gesynchroniseerd via API-Football",
      statsScore:"Score",
      statsStatus:"Status",
      statsRound:"Ronde",
      statsKickoff:"Aftrap",
      statsPlayersHeading:"Spelers",
      statsNoPlayers:"Nog geen spelerstatistieken voor deze wedstrijd.",
      statsColTeam:"Team",
      statsColPlayer:"Speler",
      statsColPoints:"Punten",
      statsFinalScore:"Eindstand",
      statsBadgeSaved:"Opgeslagen",
      statsBadgeSync:"Live",
    },
    rankingTab:{
      emptyForPool:"Nog geen teams in deze pool.",
    },
    duplicateRegistration:"Dit e-mailadres heeft al een team in deze competitie.",
    registerDuplicateToastHint:"Ga naar het tabblad Mijn team om je team bij te werken. Je wordt nu daarheen gebracht.",
    registerSignInHint:"Log in via Mijn team om je pools te zien en je team in te schrijven.",
    registerNoPoolsTitle:"Je zit nog in geen pool",
    registerNoPoolsBody:
      "Neem deel via een uitnodiging of via de openbare competitielijst, en schrijf je daarna hier in. Pools die je zelf aanmaakt beheer je in het tabblad Competitie.",
    registerNoPoolsOwnPoolWarning:
      "Je kunt geen team inschrijven voor een competitie die je zelf hebt aangemaakt — alleen genodigden (na het accepteren van de uitnodiging) kunnen zich daar inschrijven.",
    registerCreatePoolCta:"Competitie aanmaken",
    registerJoinPoolCta:"Deelnemen",
    registerStep1Intro:"Kies de pool waarvoor je je team inschrijft. Alleen pools waar je lid bent geworden (bijv. via uitnodiging)—niet pools die je zelf hebt aangemaakt. Dezelfde keuze wordt onthouden voor Mijn team.",
    editMyTeamTab:{
      pickCompetitionTitle:"Kies een competitie",
      pickCompetitionIntro:
        "Alleen pools waar je lid bent of waarvoor je al een team hebt ingeschreven, staan in deze lijst—niet elke openbare competitie. Pools die je alleen organiseert (zonder hier zelf een team) verschijnen hier niet.",
      pickCompetitionRemember:"Deze keuze wordt onthouden voor deze browsersessie.",
      noTeamInPoolTitle:"Geen team in deze pool",
      noTeamInPoolDescription:
        "Schrijf je eerst in via het tabblad Inschrijven met dit e-mailadres, of kies een andere pool waarvoor je al een team hebt.",
    },
    adminAnalytics:{
      title:"Analytics",
      intro:"Live totalen uit de database: pools, inschrijvingen, uitnodigingen en voetbal-/scoringdata.",
      refresh:"Vernieuwen",
      loading:"Analytics laden…",
      generatedAt:"Laatst opgehaald",
      loadError:"Kon analytics niet laden.",
      secPools:"Pools & teams",
      secEngagement:"Lidmaatschap & uitnodigingen",
      secData:"API-Football data",
      secScoring:"Wedstrijden & scoring",
      secTopPools:"Pools met de meeste teams",
      secRecent:"Recente team-inschrijvingen",
      colPool:"Pool",
      colTeams:"Teams",
      colOwner:"Eigenaar",
      colWhen:"Tijdstip",
      colEmail:"E-mail",
      colTeam:"Team",
      colCompetition:"Pool-id",
      platform:"Platform",
    },
    registerOnlyNonOwnedPools:"Schrijf je hier alleen in voor pools waar je lid bent (uitnodiging of openbare deelname)—niet voor pools die je zelf beheert.",
    registerInviteBanner:"Je schrijft je in voor de pool:",
    countdownTo:"AFTELLEN NAAR HET WK", days:"Dagen",hours:"Uren",minutes:"Min",seconds:"Sec", started:"Het WK is begonnen!",
    matchSchedule:"Wedstrijdschema",groups:"Groepen",knockout:"Knockout-fase",
    r16:"Achtste finales",qr:"Kwartfinales",qf:"Kwartfinales",sf:"Halve finales",final:"Finale",thirdp:"Troostfinale", pts:"Ptn",
    noParticipants:"Nog geen deelnemers", register1:"Inschrijven – Stap 1",register2:"Inschrijven – Stap 2",
    name:"Jouw naam",teamName:"Teamnaam",email:"E-mail",system:"Spelsysteem",
    next:"Volgende",back:"Terug",submit:"Team inschrijven",
    pickPlayers:"Kies per positie 1 speler uit een land — elk land slechts 1x per team", selectCountry:"Selecteer land", countryTaken:"Land al gekozen",
    deadlinePassed:"De inschrijfdeadline (10 juni 2026) is verstreken.", deadlineBefore:"Inschrijfdeadline:",
    successReg:"Je team is succesvol ingeschreven! 🎉",
    adminLogin:"Beheer – Inloggen",password:"Wachtwoord",login:"Inloggen",wrongPw:"Onjuist wachtwoord",
    adminPanel:"Puntenbeheer",pointsManagement:"Puntenbeheer",poolPointsHint:"Pas punten en teams aan voor deelnemers in jouw pool. De globale inschrijfdeadline (hele site) stelt alleen de superadmin in onder Beheer.",poolPointsSelectPool:"Jouw pool",exportExcel:"Exporteer naar Excel",logout:"Uitloggen",save:"Opslaan",saved:"Opgeslagen",
    noTeamsYet:"Nog geen teams ingeschreven",
    pos:{keeper:"Doelman",def:"Verdediger",mid:"Middenvelder",att:"Aanvaller",coach:"Coach"},
    resultsPage:"Uitslagen volgen binnenkort",
    timezoneInfo:"Tijden in tijdzone:",changeTz:"Andere tijdzone",groupLabel:"Groep",playerNamePlaceholder:"Naam van de speler",fillPlayerNames:"Vul alle spelernamen in",searchPlaceholder:"Zoek team...",coachNamePlaceholder:"Naam van de bondscoach (bijv. Ronald Koeman)",fillCoachName:"Vul de naam van de bondscoach in",duplicateEmail:"Dit e-mailadres is al geregistreerd. Eén team per e-mailadres toegestaan.",knockoutInfo:"De knockout-wedstrijden worden ingevuld zodra de groepsfase is afgelopen.",tbd:"Nog te bepalen",unsaved:"Niet opgeslagen",savingAutosave:"Opslaan…",deadlineConfig:"Inschrijfdeadline instellen",deadlineDateLabel:"Datum & tijd",deadlineDisplayLabel:"Weergegeven tekst",saveDeadline:"Deadline opslaan",confirmLogout:"Weet je zeker dat je wilt uitloggen uit het beheerpaneel?",cancel:"Annuleren",settings:"Instellingen",themeLabel:"Thema",darkTheme:"Donker",lightTheme:"Licht",languageLabel:"Taal",timezoneLabel:"Tijdzone",adminLoggedIn:"Ingelogd als beheerder",superadminLabel:"Superadmin",superadminHint:"Volledige toegang. Alleen dit account ziet het Beheer-tabblad.",openAdminPanel:"Beheer openen",changeInSettings:"Wijzig in instellingen ⚙️",edit:"Bewerken",editTeam:"Team bewerken",teamName:"Teamnaam",userName:"Naam",system:"Systeem",fillRequired:"Vul alle verplichte velden in",choosePlayer:"Kies speler",chooseCoach:"Kies bondscoach",playerNameManual:"Naam (handmatig)",rulesContent:{title:"Spelregels",intro:"Welkom bij de WK 2026 Poule! Hier lees je hoe het spel werkt, hoe je punten verdient en wat de belangrijkste regels zijn.",howTitle:"Hoe werkt het?",how1:"Schrijf je in vóór de inschrijfdeadline.",how2:"Kies een spelsysteem (4-3-3, 4-4-2 of 3-4-3).",how3:"Kies per positie één speler uit een land. Elk land mag je maar 1x gebruiken — maar andere deelnemers mogen hetzelfde land ook kiezen.",how4:"Kies een bondscoach — het land van de coach telt ook als één van jouw landkeuzes.",how5:"Tijdens het toernooi verdien je punten op basis van prestaties van je gekozen landen en spelers.",how6:"Wie aan het einde de meeste punten heeft, wint!",deadlineTitle:"Inschrijfdeadline",deadlineText:"Inschrijven kan tot:",deadlineNote:"Daarna is inschrijven niet meer mogelijk en kun je je team niet meer wijzigen.",pointsTitle:"Puntentelling",pointsIntro:"Punten verschillen per positie. Aanvallers verdienen meer voor doelpunten, verdedigers voor clean sheets, enz.",eventCol:"Gebeurtenis",evWin:"Wedstrijd gewonnen (land)",evDraw:"Gelijkspel (land)",evGoal:"Doelpunt",evAssist:"Assist",evClean:"Geen tegendoelpunt",evPenalty:"Penalty gestopt",evOg:"Eigen doelpunt",evYellow:"Gele kaart",ev2Yellow:"2x geel = rood",evRed:"Directe rode kaart",evSub:"Geslaagde wissel (doelpunt na wissel)",evChampion:"Wereldkampioen",rulesTitle:"Belangrijke regels",rule1:"Je kunt je inschrijven met één e-mailadres — één team per persoon.",rule2:"Binnen jouw team mag elk land maar één keer voorkomen.",rule3:"Andere deelnemers mogen wel hetzelfde land kiezen — er is geen exclusiviteit tussen teams.",rule4:"Na de inschrijfdeadline kun je je team niet meer wijzigen.",rule5:"Punten worden continu bijgewerkt door de beheerder tijdens het toernooi.",rule6:"Bij gelijke eindstand wint degene met de meeste doelpunten van zijn aanvallers.",captainTitle:"Aanvoerder",captainText:"Jij kiest één speler als aanvoerder. Als zijn land wereldkampioen wordt, verdient jouw aanvoerder de kampioenspunten — net als al je andere spelers van dat land. De aanvoerder geeft geen extra bonuspunten bovenop.",captainNote:"Je aanvoerder is zichtbaar met een oranje band op je opstellingsbord. Kies verstandig — een favoriet land geeft de beste kans op de bonus!",exampleTitle:"Voorbeeldteam (4-3-3)",exampleIntro:"Een geldig teamvoorbeeld. Elk land maar 1x gebruikt, aanvoerder gemarkeerd met het bandje.",exampleNote:"In dit voorbeeld wordt Argentinië twee keer gebruikt — Lautaro Martínez als aanvaller én Scaloni als coach. Dat is niet toegestaan. Elk land maar 1x.",mistakesTitle:"Veelvoorkomende fouten",contactText:"Heb je vragen of zie je een fout in de puntentelling? Neem contact op met de organisator van de poule.",privacyTitle:"Privacy",privacyText:"Je e-mailadres wordt alleen gebruikt om dubbele inschrijvingen te voorkomen en wordt niet gedeeld met derden."}
  },
  en: { title:"WC 2026 POOL", subtitle:"USA • CANADA • MEXICO",
    tabs:{ranking:"Ranking",matches:"Matches",matches2:"Matches 2",results:"Results",teams:"Teams",competitions:"All competitions",register:"Register",register2:"Register 2",edit:"My Team",rules:"Rules",competition:"Competition",poolPoints:"ManagePoints",admin:"Admin"},
    competitionTab:{
      title:"Competition",
      intro:"Pools you create are yours to manage. Share the slug so others register in the same competition.",
      signInHint:"Sign in (My Team) to create and manage your pools.",
      goToMyTeam:"Go to My Team",
      createPool:"Create a pool",
      slugPh:"slug (e.g. office-2026)",
      namePh:"Display name",
      seasonPh:"season (optional)",
      submitCreate:"Create",
      yourPools:"Your competitions",
      noPoolsYet:"No pools yet — create one above.",
      poolIdLabel:"Pool id",
      slugLabel:"Slug",
      startsLabel:"Starts",
      teamsLabel:"Teams registered",
      fixturesTitle:"Fixture links (API Football id)",
      saveMap:"Save",
      noMappings:"No fixture rows for this pool yet (they appear when the competition is seeded).",
      manage:"Manage",
      selected:"Selected",
      delete:"Delete",
      createFailed:"Could not create pool",
      deleteFailed:"Could not delete",
      fixtureIdPositive:"Fixture id must be a positive integer.",
      fixtureDup:"That API fixture id is already used in this pool.",
      mappingFailed:"Mapping update failed",
      slugNameRequired:"Slug and name are required.",
      leagueTypeLabel:"Competition type (API-Football)",
      leagueTypePlaceholder:"— choose type —",
      leagueTypeRequired:"Choose a competition type.",
      leagueTypeReadonlyHint:"Competition type cannot be changed after the pool is created.",
      confirmDelTitle:"Delete competition?",
      confirmDelBody:"This removes the pool when allowed (linked teams may block deletion).",
      confirmDelete:"Delete",
      editSection:"Edit",
      metadataLabel:"Metadata (JSON)",
      metadataHint:"Optional: extra settings as valid JSON.",
      updateFailed:"Save failed",
      updated:"Saved",
      clearStart:"No start date (clear)",
      metadataInvalid:"Metadata must be valid JSON (an object).",
      invitesTitle:"Email invitations",
      invitesHelp:"We send a link (configure Brevo or Resend + PUBLIC_APP_URL on the API). Recipients sign in with that email, then use Register.",
      inviteEmailPh:"friend@example.com",
      sendInvite:"Send invite",
      invitePending:"pending",
      inviteAccepted:"accepted",
      noInvitesYet:"No invites for this pool yet.",
      inviteEmailRequired:"Enter an email address.",
      inviteNoEmail:"Email not sent. Copy the link; details from the API appear below.",
      inviteSendFailed:"Invite failed",
      importFixturesTitle:"Import fixtures (API-Football)",
      importFixturesHint:"Fetch the full schedule from API-Football and save it as fixture mappings for this pool. Requires API_FOOTBALL_KEY on the server. Optional: league and season IDs below; otherwise use metadata.api_football in the JSON above.",
      importFixturesLeagueLabel:"API league id",
      importFixturesSeasonLabel:"Season (year)",
      importFixturesButton:"Fetch & save fixtures",
      importFixturesBusy:"Importing…",
      importFixturesSuccess:"Saved {n} fixtures ({total} from API).",
      importFixturesNone:"No rows imported.",
      fetchAllFixtureSquadsButton:"Fetch players for all fixtures",
      fetchAllFixtureSquadsBusy:"Starting…",
      fetchAllFixtureSquadsHint:"Starts a background job on the server: one API call per fixture, then a 3 second pause. Sides already stored for this league, season, and team name are skipped.",
      fetchAllFixtureSquadsStarted:"Squad members are being fetched.",
      fetchAllFixtureSquadsFailed:"Could not start squad fetch",
      fetchAllFixtureSquadsNoMappings:"No fixtures with a valid API fixture id yet.",
    },
    allCompetitionsTab:{
      title:"All competitions",
      intro:"Every public pool, pool start time (registration closes then), and who created it. If registration is still open, jump straight to Register for that pool.",
      empty:"No competitions found.",
      openBadge:"Registration open",
      closedBadge:"Closed",
      organizer:"Organizer",
      teams:"Teams registered",
      deadline:"Registration closes (pool start)",
      starts:"Pool start",
      created:"Pool created",
      poolId:"Pool id",
      slugLabel:"Slug",
      metadata:"Metadata",
      registerCta:"Register for this competition",
      joining:"Joining…",
      closedHint:"This pool has started — registration is closed.",
      ownerIdOnly:"Organizer account",
      platformPool:"Platform / seeded pool",
      joinOwnPoolError:
        "This is a pool you created. Manage it under Competition—you can’t join it here as a player. Invite others by email if they should register a team.",
    },
    matches2Tab:{
      selectCompetition:"Competition",
      noCompetitionsList:"No competitions available.",
      needCompetition:"Choose a competition first (All competitions or Register) to load the schedule.",
      empty:"No fixture mappings for this pool yet.",
      loadError:"Could not load fixtures.",
      noKickoffYet:"Date TBD",
      noGroupTeams:"No group-stage team names in fixture data yet.",
      fromMappings:"from pool schedule",
      competitionScheduleNote:"Times follow this competition’s official schedule timezone (not your profile timezone).",
      noPoolStartDate:"This pool has no start date yet — the organizer can set it when editing the pool.",
      viewStatistics:"View Statistics",
      statsDialogTitle:"Match statistics",
      statsClose:"Close",
      statsSourceDatabase:"Loaded from saved data",
      statsSourceApi:"Synced from API-Football",
      statsScore:"Score",
      statsStatus:"Status",
      statsRound:"Round",
      statsKickoff:"Kickoff",
      statsPlayersHeading:"Players",
      statsNoPlayers:"No player statistics rows for this fixture yet.",
      statsColTeam:"Team",
      statsColPlayer:"Player",
      statsColPoints:"Points",
      statsFinalScore:"Final score",
      statsBadgeSaved:"Saved",
      statsBadgeSync:"Live sync",
    },
    rankingTab:{
      emptyForPool:"No teams registered in this pool yet.",
    },
    duplicateRegistration:"This email already has a team in this competition.",
    registerDuplicateToastHint:"Go to the My team tab to update your squad. Taking you there now.",
    registerSignInHint:"Sign in via My Team to see your pools and register your squad.",
    registerNoPoolsTitle:"You're not in any pool yet",
    registerNoPoolsBody:
      "Join using an invitation link or from the public competition list, then register your team here. Pools you create are managed in the Competition tab.",
    registerNoPoolsOwnPoolWarning:
      "You cannot register a team in a competition you created yourself—only people who join via your email invitation can register a team there.",
    registerCreatePoolCta:"Create competition",
    registerJoinPoolCta:"Participate",
    registerStep1Intro:"Choose the pool for your team. Only pools you joined (for example after an invitation)—not pools you created yourself. The same choice is remembered for My Team.",
    editMyTeamTab:{
      pickCompetitionTitle:"Choose a competition",
      pickCompetitionIntro:
        "Only pools you belong to as a member, or where you already have a team, are listed—not every public competition. Pools you only organize (without a team in that pool) are not shown here.",
      pickCompetitionRemember:"This choice is remembered for this browser session.",
      noTeamInPoolTitle:"No team registered for this pool",
      noTeamInPoolDescription:
        "Register on the Register tab with this email first, or choose another competition where you already have a team.",
    },
    adminAnalytics:{
      title:"Analytics",
      intro:"Live totals from the database: competitions, registrations, invitations, and football/scoring footprint.",
      refresh:"Refresh",
      loading:"Loading analytics…",
      generatedAt:"Last fetched",
      loadError:"Could not load analytics.",
      secPools:"Pools & teams",
      secEngagement:"Membership & invites",
      secData:"API-Football data",
      secScoring:"Matches & scoring",
      secTopPools:"Pools with most teams",
      secRecent:"Recent team sign-ups",
      colPool:"Pool",
      colTeams:"Teams",
      colOwner:"Owner",
      colWhen:"When",
      colEmail:"Email",
      colTeam:"Team",
      colCompetition:"Pool id",
      platform:"Platform",
    },
    registerOnlyNonOwnedPools:"Register here only for pools you joined (invitation or public list)—not pools you created yourself.",
    registerInviteBanner:"You are registering for pool:",
    countdownTo:"COUNTDOWN TO THE WORLD CUP", days:"Days",hours:"Hours",minutes:"Min",seconds:"Sec", started:"The World Cup has started!",
    matchSchedule:"Match Schedule",groups:"Groups",knockout:"Knockout stage",
    r16:"Round of 16",qr:"Quarter-finals",qf:"Quarter-finals",sf:"Semi-finals",final:"Final",thirdp:"3rd place", pts:"Pts",
    noParticipants:"No participants yet", register1:"Register – Step 1",register2:"Register – Step 2",
    name:"Your name",teamName:"Team name",email:"Email",system:"Formation",
    next:"Next",back:"Back",submit:"Submit team",
    pickPlayers:"Pick 1 player per position from a country — each country only once per team", selectCountry:"Select country", countryTaken:"Country already chosen",
    deadlinePassed:"Registration deadline (June 10, 2026) has passed.", deadlineBefore:"Registration deadline:",
    successReg:"Your team has been registered! 🎉",
    adminLogin:"Admin login",password:"Password",login:"Log in",wrongPw:"Wrong password",
    adminPanel:"Points management",pointsManagement:"Points management",poolPointsHint:"Edit points and squads for teams in your pool. The site-wide registration deadline is only editable by the superadmin in the Admin tab.",poolPointsSelectPool:"Your pool",exportExcel:"Export to Excel",logout:"Log out",save:"Save",saved:"Saved",
    noTeamsYet:"No teams registered yet",
    pos:{keeper:"Goalkeeper",def:"Defender",mid:"Midfielder",att:"Forward",coach:"Coach"},
    resultsPage:"Results coming soon",
    timezoneInfo:"Times in timezone:",changeTz:"Change timezone",groupLabel:"Group",playerNamePlaceholder:"Player name",fillPlayerNames:"Fill in all player names",searchPlaceholder:"Search team...",coachNamePlaceholder:"Coach name (e.g. Ronald Koeman)",fillCoachName:"Fill in the coach name",duplicateEmail:"This email is already registered. One team per email allowed.",knockoutInfo:"Knockout matches will appear once the group stage ends.",tbd:"TBD",unsaved:"Unsaved",savingAutosave:"Saving…",deadlineConfig:"Set registration deadline",deadlineDateLabel:"Date & time",deadlineDisplayLabel:"Displayed text",saveDeadline:"Save deadline",confirmLogout:"Are you sure you want to log out of the admin panel?",cancel:"Cancel",settings:"Settings",themeLabel:"Theme",darkTheme:"Dark",lightTheme:"Light",languageLabel:"Language",timezoneLabel:"Timezone",adminLoggedIn:"Logged in as admin",superadminLabel:"Superadmin",superadminHint:"Full access. Only this account sees the Admin tab.",openAdminPanel:"Open admin panel",changeInSettings:"Change in settings ⚙️",edit:"Edit",editTeam:"Edit team",teamName:"Team name",userName:"Name",system:"System",fillRequired:"Fill in all required fields",choosePlayer:"Choose player",chooseCoach:"Choose coach",playerNameManual:"Name (manual)",rulesContent:{title:"Game Rules",intro:"Welcome to the WC 2026 Pool! Below you can read how the game works, how to earn points, and the most important rules.",howTitle:"How does it work?",how1:"Register before the deadline.",how2:"Choose a formation (4-3-3, 4-4-2 or 3-4-3).",how3:"Pick a player from a country for each position. Each country can only appear once in your team — but other participants may choose the same country.",how4:"Choose a head coach — the coach's country also counts as one of your country slots.",how5:"During the tournament, you earn points based on the performance of your chosen countries and players.",how6:"The person with the most points at the end wins!",deadlineTitle:"Registration deadline",deadlineText:"You can register until:",deadlineNote:"After that, registration closes and your team is final.",pointsTitle:"Points system",pointsIntro:"Points differ per position. Attackers get more points for goals, defenders for clean sheets, etc.",eventCol:"Event",evWin:"Match won (country)",evDraw:"Draw (country)",evGoal:"Goal",evAssist:"Assist",evClean:"Clean sheet",evPenalty:"Penalty saved",evOg:"Own goal",evYellow:"Yellow card",ev2Yellow:"2 yellows = red",evRed:"Direct red card",evSub:"Successful substitution (goal after sub)",evChampion:"World Champion",rulesTitle:"Important rules",rule1:"You can register with one email address — one team per person.",rule2:"Within your team, each country can only appear once.",rule3:"Other participants can pick the same country — no exclusivity between teams.",rule4:"After the deadline, your team cannot be changed.",rule5:"Points are updated continuously by the admin during the tournament.",rule6:"In case of a tie, whoever has the most goals from their attackers wins.",contactText:"Got questions or spotted an error in the points? Contact the pool organizer.",privacyTitle:"Privacy",privacyText:"Your email address is only used to prevent duplicate registrations and is not shared with third parties."}
  },
  es: { title:"QUINIELA MUNDIAL 2026", subtitle:"USA • CANADA • MEXICO",
    tabs:{ranking:"Clasificación",matches:"Partidos",matches2:"Partidos 2",results:"Resultados",teams:"Equipos",competitions:"Todas las competiciones",register:"Inscribirse",register2:"Inscribirse 2",edit:"Mi equipo",rules:"Reglas",competition:"Competición",poolPoints:"Puntos",admin:"Admin"},
    matches2Tab:{
      selectCompetition:"Competición",
      noCompetitionsList:"No hay competiciones disponibles.",
      needCompetition:"Elige una competición primero (Todas las competiciones o Inscribirse).",
      empty:"Aún no hay partidos vinculados para esta pool.",
      loadError:"Error al cargar.",
      noKickoffYet:"Fecha por definir",
      noGroupTeams:"Aún no hay equipos de fase de grupos en los datos.",
      fromMappings:"del calendario de la pool",
      competitionScheduleNote:"Los horarios usan la zona oficial de esta competición (no la de tu perfil).",
      noPoolStartDate:"Esta pool aún no tiene fecha de inicio; el organizador puede definirla al editar.",
      viewStatistics:"Ver estadísticas",
    },
    countdownTo:"CUENTA ATRÁS AL MUNDIAL", days:"Días",hours:"Horas",minutes:"Min",seconds:"Seg", started:"¡El Mundial ha comenzado!",
    matchSchedule:"Calendario",groups:"Grupos",knockout:"Eliminatorias",
    r16:"Octavos",qr:"Cuartos",qf:"Cuartos",sf:"Semifinales",final:"Final",thirdp:"3er puesto", pts:"Pts",
    noParticipants:"Sin participantes aún", register1:"Inscripción – Paso 1",register2:"Inscripción – Paso 2",
    name:"Tu nombre",teamName:"Nombre del equipo",email:"Email",system:"Sistema",
    next:"Siguiente",back:"Atrás",submit:"Enviar equipo",
    pickPlayers:"Elige 1 jugador por posición de un país — cada país solo una vez por equipo", selectCountry:"Selecciona país", countryTaken:"País ya elegido",
    deadlinePassed:"La fecha límite (10 de junio de 2026) ha pasado.", deadlineBefore:"Fecha límite:",
    successReg:"¡Tu equipo se ha registrado! 🎉",
    adminLogin:"Acceso admin",password:"Contraseña",login:"Entrar",wrongPw:"Contraseña incorrecta",
    adminPanel:"Gestión de puntos",pointsManagement:"Gestión de puntos",poolPointsHint:"Edita puntos y plantillas de los equipos en tu pool. La fecha límite global solo la configura el superadmin en Admin.",poolPointsSelectPool:"Tu pool",exportExcel:"Exportar a Excel",logout:"Cerrar sesión",save:"Guardar",saved:"Guardado",
    noTeamsYet:"Aún no hay equipos",
    pos:{keeper:"Portero",def:"Defensa",mid:"Centrocampista",att:"Delantero",coach:"DT"},
    resultsPage:"Resultados próximamente",
    timezoneInfo:"Horarios en zona:",changeTz:"Cambiar zona",groupLabel:"Grupo",playerNamePlaceholder:"Nombre del jugador",fillPlayerNames:"Completa todos los nombres",searchPlaceholder:"Buscar equipo...",coachNamePlaceholder:"Nombre del DT (ej. Ronald Koeman)",fillCoachName:"Ingresa el nombre del DT",duplicateEmail:"Este email ya está registrado. Un equipo por email.",knockoutInfo:"Los partidos eliminatorios aparecerán al finalizar la fase de grupos.",tbd:"Por definir",unsaved:"Sin guardar",savingAutosave:"Guardando…",deadlineConfig:"Configurar fecha límite",deadlineDateLabel:"Fecha y hora",deadlineDisplayLabel:"Texto mostrado",saveDeadline:"Guardar fecha",confirmLogout:"¿Seguro que quieres cerrar sesión del panel?",cancel:"Cancelar",settings:"Configurações",themeLabel:"Tema",darkTheme:"Escuro",lightTheme:"Claro",languageLabel:"Idioma",timezoneLabel:"Fuso horário",adminLoggedIn:"Logado como admin",changeInSettings:"Alterar nas configurações ⚙️",edit:"Editar",editTeam:"Editar time",teamName:"Nome do time",userName:"Nome",system:"Sistema",fillRequired:"Preencha todos os campos",choosePlayer:"Escolher jogador",chooseCoach:"Escolher técnico",playerNameManual:"Nome (manual)",rulesContent:{title:"Regras do jogo",intro:"Bem-vindo ao bolão da Copa do Mundo 2026! Veja como funciona e como ganhar pontos.",howTitle:"Como funciona?",how1:"Inscreva-se antes do prazo.",how2:"Escolha uma formação (4-3-3, 4-4-2 ou 3-4-3).",how3:"Escolha um país para cada posição. Cada país só pode ser escolhido uma vez por pessoa.",how4:"Informe o nome do técnico.",how5:"Durante o torneio você ganha pontos com base no desempenho.",how6:"Quem tiver mais pontos no final ganha!",deadlineTitle:"Prazo de inscrição",deadlineText:"Inscrições até:",deadlineNote:"Após o prazo seu time não pode ser alterado.",pointsTitle:"Sistema de pontos",pointsIntro:"Os pontos variam por posição. Atacantes ganham mais por gols, zagueiros por jogos sem sofrer gol.",eventCol:"Evento",evWin:"Jogo ganho (país)",evDraw:"Empate (país)",evGoal:"Gol",evAssist:"Assistência",evClean:"Sem sofrer gol",evPenalty:"Pênalti defendido",evOg:"Gol contra",evYellow:"Cartão amarelo",ev2Yellow:"2 amarelos = vermelho",evRed:"Vermelho direto",evSub:"Substituição certa (gol após substituição)",evChampion:"Campeão Mundial",rulesTitle:"Regras importantes",rule1:"Inscrição com um email — um time por pessoa.",rule2:"No seu time cada país só pode aparecer uma vez.",rule3:"Outros participantes podem escolher o mesmo país.",rule4:"Após o prazo seu time não pode ser alterado.",rule5:"Os pontos são atualizados continuamente pelo admin.",rule6:"Em caso de empate, quem tiver mais gols dos atacantes ganha.",prizesTitle:"Prêmios & contato",prizesText:"Os prêmios são anunciados pelo organizador. Inscrições e pagamentos são feitos separadamente.",contactText:"Dúvidas? Contate o organizador.",privacyTitle:"Privacidade",privacyText:"Seu email é usado apenas para evitar inscrições duplicadas.",captainTitle:"Capitão",captainText:"Você escolhe um jogador como capitão. Se o país dele for campeão, ele ganha os pontos de campeão igual aos outros jogadores daquele país.",captainNote:"Seu capitão aparece com uma braçadeira laranja. Escolha com sabedoria!",exampleTitle:"Time exemplo (4-3-3)",exampleIntro:"Exemplo válido: cada país uma vez, capitão com braçadeira.",exampleNote:"Argentina usada duas vezes é erro — não permitido.",mistakesTitle:"Erros comuns"},settings:"Ajustes",themeLabel:"Tema",darkTheme:"Oscuro",lightTheme:"Claro",languageLabel:"Idioma",timezoneLabel:"Zona horaria",adminLoggedIn:"Sesión iniciada como admin",changeInSettings:"Cambiar en ajustes ⚙️",edit:"Editar",editTeam:"Editar equipo",teamName:"Nombre del equipo",userName:"Nombre",system:"Sistema",fillRequired:"Completa todos los campos",choosePlayer:"Elige jugador",chooseCoach:"Elige DT",playerNameManual:"Nombre (manual)",rulesContent:{title:"Reglas del juego",intro:"¡Bienvenido a la quiniela del Mundial 2026! Aquí encontrarás cómo funciona, cómo ganar puntos y las reglas principales.",howTitle:"¿Cómo funciona?",how1:"Inscríbete antes de la fecha límite.",how2:"Elige una formación (4-3-3, 4-4-2 o 3-4-3).",how3:"Elige un país para cada posición. Cada país solo puede elegirse una vez por persona.",how4:"Indica el nombre del DT.",how5:"Durante el torneo ganas puntos según el rendimiento de tus países y jugadores.",how6:"¡Gana quien tenga más puntos al final!",deadlineTitle:"Fecha límite de inscripción",deadlineText:"Puedes inscribirte hasta:",deadlineNote:"Después no podrás modificar tu equipo.",pointsTitle:"Sistema de puntos",pointsIntro:"Los puntos varían según la posición. Atacantes ganan más por goles, defensas por arcos en cero, etc.",eventCol:"Evento",evWin:"Partido ganado (país)",evDraw:"Empate (país)",evGoal:"Gol",evAssist:"Asistencia",evClean:"Arco en cero",evPenalty:"Penalty atajado",evOg:"Gol en contra",evYellow:"Tarjeta amarilla",ev2Yellow:"2 amarillas = roja",evRed:"Roja directa",evSub:"Cambio exitoso (gol tras cambio)",evChampion:"Campeón mundial",rulesTitle:"Reglas importantes",rule1:"Puedes inscribirte con un email — un equipo por persona.",rule2:"Dentro de tu equipo, cada país solo puede aparecer una vez.",rule3:"Otros participantes pueden elegir el mismo país.",rule4:"Tras la fecha límite no puedes modificar tu equipo.",rule5:"Los puntos se actualizan continuamente por el admin durante el torneo.",rule6:"En caso de empate, gana quien tenga más goles de sus atacantes.",prizesTitle:"Premios y contacto",prizesText:"Los premios los anuncia el organizador de la quiniela. La inscripción y pagos se gestionan aparte.",contactText:"¿Preguntas o ves un error? Contacta al organizador.",privacyTitle:"Privacidad",privacyText:"Tu email solo se usa para evitar inscripciones duplicadas y no se comparte con terceros.",captainTitle:"Capitán",captainText:"Eliges un jugador como capitán. Si su país es campeón del mundo, gana los puntos de campeón igual que tus otros jugadores de ese país.",captainNote:"Tu capitán aparece con un brazalete naranja. ¡Elige con sabiduría!",exampleTitle:"Equipo ejemplo (4-3-3)",exampleIntro:"Ejemplo válido: cada país una vez, capitán con brazalete.",exampleNote:"Argentina usada dos veces es un error — no está permitido.",mistakesTitle:"Errores comunes"}
  },
  fr: { title:"COUPE DU MONDE 2026", subtitle:"USA • CANADA • MEXICO",
    tabs:{ranking:"Classement",matches:"Matchs",matches2:"Matchs 2",results:"Résultats",teams:"Équipes",competitions:"Toutes les compétitions",register:"Inscription",register2:"Inscription 2",edit:"Mon équipe",rules:"Règles",competition:"Compétition",poolPoints:"Points",admin:"Admin"},
    matches2Tab:{
      selectCompetition:"Compétition",
      noCompetitionsList:"Aucune compétition disponible.",
      needCompetition:"Choisis d'abord une compétition (Toutes les compétitions ou Inscription).",
      empty:"Pas encore de matchs liés pour cette pool.",
      loadError:"Échec du chargement.",
      noKickoffYet:"Date à confirmer",
      noGroupTeams:"Pas encore d'équipes de phase de groupes dans les données.",
      fromMappings:"du calendrier de la pool",
      competitionScheduleNote:"Les horaires suivent le fuseau officiel de cette compétition (pas celui de ton profil).",
      noPoolStartDate:"Cette pool n’a pas encore de date de début — l’organisateur peut la définir à l’édition.",
      viewStatistics:"Voir les statistiques",
    },
    countdownTo:"COMPTE À REBOURS – COUPE DU MONDE", days:"Jours",hours:"Heures",minutes:"Min",seconds:"Sec", started:"La Coupe du Monde a commencé!",
    matchSchedule:"Calendrier",groups:"Groupes",knockout:"Phase à élimination",
    r16:"Huitièmes",qr:"Quarts",qf:"Quarts",sf:"Demies",final:"Finale",thirdp:"3e place", pts:"Pts",
    noParticipants:"Aucun participant", register1:"Inscription – Étape 1",register2:"Inscription – Étape 2",
    name:"Votre nom",teamName:"Nom d'équipe",email:"E-mail",system:"Système",
    next:"Suivant",back:"Retour",submit:"Envoyer l'équipe",
    pickPlayers:"1 joueur par poste d'un pays — chaque pays une seule fois par équipe", selectCountry:"Choisir un pays", countryTaken:"Pays déjà pris",
    deadlinePassed:"Date limite (10 juin 2026) dépassée.", deadlineBefore:"Date limite:",
    successReg:"Équipe inscrite! 🎉",
    adminLogin:"Connexion admin",password:"Mot de passe",login:"Se connecter",wrongPw:"Mot de passe erroné",
    adminPanel:"Gestion des points",pointsManagement:"Gestion des points",poolPointsHint:"Modifiez les points et les équipes des participants de votre pool. La date limite globale est réservée au superadmin (Admin).",poolPointsSelectPool:"Votre pool",exportExcel:"Exporter Excel",logout:"Déconnexion",save:"Enregistrer",saved:"Enregistré",
    noTeamsYet:"Pas encore d'équipes",
    pos:{keeper:"Gardien",def:"Défenseur",mid:"Milieu",att:"Attaquant",coach:"Coach"},
    resultsPage:"Résultats bientôt",
    timezoneInfo:"Horaires en fuseau:",changeTz:"Changer fuseau",groupLabel:"Groupe",playerNamePlaceholder:"Nom du joueur",fillPlayerNames:"Remplissez tous les noms",searchPlaceholder:"Rechercher équipe...",coachNamePlaceholder:"Nom du sélectionneur (p. ex. Didier Deschamps)",fillCoachName:"Entrez le nom du sélectionneur",duplicateEmail:"Cet e-mail est déjà enregistré. Une équipe par e-mail.",knockoutInfo:"Les matchs à élimination apparaîtront après la phase de groupes.",tbd:"À définir",unsaved:"Non enregistré",savingAutosave:"Enregistrement…",deadlineConfig:"Configurer date limite",deadlineDateLabel:"Date & heure",deadlineDisplayLabel:"Texte affiché",saveDeadline:"Enregistrer",confirmLogout:"Voulez-vous vraiment vous déconnecter de l'admin?",cancel:"Annuler",settings:"Paramètres",themeLabel:"Thème",darkTheme:"Sombre",lightTheme:"Clair",languageLabel:"Langue",timezoneLabel:"Fuseau horaire",adminLoggedIn:"Connecté en tant qu'admin",changeInSettings:"Modifier dans les paramètres ⚙️",edit:"Modifier",editTeam:"Modifier équipe",teamName:"Nom de l'équipe",userName:"Nom",system:"Système",fillRequired:"Remplissez tous les champs",choosePlayer:"Choisir joueur",chooseCoach:"Choisir sélectionneur",playerNameManual:"Nom (manuel)",rulesContent:{title:"Règles du jeu",intro:"Bienvenue dans le pool Coupe du Monde 2026! Vous trouverez ci-dessous comment ça marche et comment gagner des points.",howTitle:"Comment ça marche?",how1:"Inscrivez-vous avant la date limite.",how2:"Choisissez une formation (4-3-3, 4-4-2 ou 3-4-3).",how3:"Choisissez un pays pour chaque position. Chaque pays ne peut être choisi qu'une fois par personne.",how4:"Indiquez le nom du sélectionneur.",how5:"Pendant le tournoi vous gagnez des points selon les performances.",how6:"Celui qui a le plus de points à la fin gagne!",deadlineTitle:"Date limite",deadlineText:"Inscriptions jusqu'au:",deadlineNote:"Après cette date votre équipe ne peut plus être modifiée.",pointsTitle:"Système de points",pointsIntro:"Les points varient par position. Les attaquants gagnent plus pour les buts, les défenseurs pour les cleansheets.",eventCol:"Événement",evWin:"Match gagné (pays)",evDraw:"Match nul (pays)",evGoal:"But",evAssist:"Passe décisive",evClean:"Cleansheet",evPenalty:"Penalty arrêté",evOg:"But contre son camp",evYellow:"Carton jaune",ev2Yellow:"2 jaunes = rouge",evRed:"Carton rouge direct",evSub:"Remplacement réussi (but après remplacement)",evChampion:"Champion du Monde",rulesTitle:"Règles importantes",rule1:"Inscription avec une adresse email — une équipe par personne.",rule2:"Dans votre équipe, chaque pays ne peut apparaître qu'une fois.",rule3:"Les autres participants peuvent choisir le même pays.",rule4:"Après la date limite, votre équipe ne peut plus être modifiée.",rule5:"Les points sont mis à jour en continu par l'admin.",rule6:"En cas d'égalité, celui qui a le plus de buts de ses attaquants gagne.",prizesTitle:"Prix & contact",prizesText:"Les prix sont annoncés par l'organisateur. La mise et les paiements sont gérés séparément.",contactText:"Des questions? Contactez l'organisateur du pool.",privacyTitle:"Vie privée",privacyText:"Votre email est uniquement utilisé pour éviter les inscriptions en double et n'est pas partagé.",captainTitle:"Capitaine",captainText:"Vous choisissez un joueur comme capitaine. Si son pays est champion du monde, il gagne les points de champion comme vos autres joueurs de ce pays.",captainNote:"Votre capitaine apparaît avec un brassard orange. Choisissez judicieusement !",exampleTitle:"Équipe exemple (4-3-3)",exampleIntro:"Exemple valide : chaque pays une fois, capitaine avec brassard.",exampleNote:"Utiliser l'Argentine deux fois est une erreur — interdit.",mistakesTitle:"Erreurs courantes"}
  },
  pt: { title:"BOLÃO COPA 2026", subtitle:"USA • CANADA • MEXICO",
    tabs:{ranking:"Classificação",matches:"Jogos",matches2:"Jogos 2",results:"Resultados",teams:"Times",competitions:"Todas as competições",register:"Inscrever",register2:"Inscrever 2",edit:"Meu time",rules:"Regras",competition:"Competição",poolPoints:"Pontos",admin:"Admin"},
    matches2Tab:{
      selectCompetition:"Competição",
      noCompetitionsList:"Nenhuma competição disponível.",
      needCompetition:"Escolha uma competição primeiro (Todas as competições ou Inscrever).",
      empty:"Ainda não há jogos vinculados para esta pool.",
      loadError:"Falha ao carregar.",
      noKickoffYet:"Data a definir",
      noGroupTeams:"Ainda não há times da fase de grupos nos dados.",
      fromMappings:"do calendário da pool",
      competitionScheduleNote:"Os horários seguem o fuso oficial desta competição (não o do seu perfil).",
      noPoolStartDate:"Esta pool ainda não tem data de início — o organizador pode definir ao editar.",
      viewStatistics:"Ver estatísticas",
    },
    countdownTo:"CONTAGEM REGRESSIVA PARA A COPA", days:"Dias",hours:"Horas",minutes:"Min",seconds:"Seg", started:"A Copa começou!",
    matchSchedule:"Calendário",groups:"Grupos",knockout:"Mata-mata",
    r16:"Oitavas",qr:"Quartas",qf:"Quartas",sf:"Semifinais",final:"Final",thirdp:"3º lugar", pts:"Pts",
    noParticipants:"Sem participantes", register1:"Inscrição – Passo 1",register2:"Inscrição – Passo 2",
    name:"Seu nome",teamName:"Nome do time",email:"E-mail",system:"Esquema",
    next:"Próximo",back:"Voltar",submit:"Enviar time",
    pickPlayers:"1 jogador por posição de um país — cada país apenas uma vez por time", selectCountry:"Selecionar país", countryTaken:"País já escolhido",
    deadlinePassed:"Prazo (10 de junho de 2026) expirou.", deadlineBefore:"Prazo:",
    successReg:"Time inscrito! 🎉",
    adminLogin:"Login admin",password:"Senha",login:"Entrar",wrongPw:"Senha errada",
    adminPanel:"Gestão de pontos",pointsManagement:"Gestão de pontos",poolPointsHint:"Edite pontos e elencos dos times na sua pool. O prazo global de inscrição só o superadmin altera em Admin.",poolPointsSelectPool:"Sua pool",exportExcel:"Exportar Excel",logout:"Sair",save:"Salvar",saved:"Salvo",
    noTeamsYet:"Nenhum time ainda",
    pos:{keeper:"Goleiro",def:"Zagueiro",mid:"Meio-campo",att:"Atacante",coach:"Técnico"},
    resultsPage:"Resultados em breve",
    timezoneInfo:"Horários no fuso:",changeTz:"Mudar fuso",groupLabel:"Grupo",playerNamePlaceholder:"Nome do jogador",fillPlayerNames:"Preencha todos os nomes",searchPlaceholder:"Buscar time...",coachNamePlaceholder:"Nome do técnico (ex. Dorival Júnior)",fillCoachName:"Digite o nome do técnico",duplicateEmail:"Este email já está registrado. Um time por email.",knockoutInfo:"Os jogos do mata-mata aparecerão após a fase de grupos.",tbd:"A definir",unsaved:"Não salvo",savingAutosave:"Salvando…",deadlineConfig:"Configurar prazo",deadlineDateLabel:"Data e hora",deadlineDisplayLabel:"Texto exibido",saveDeadline:"Salvar prazo",confirmLogout:"Tem certeza de que deseja sair do painel admin?",cancel:"Cancelar"
  },
  ar: { title:"كأس العالم 2026", subtitle:"الولايات المتحدة • كندا • المكسيك",
    tabs:{ranking:"الترتيب",matches:"المباريات",matches2:"المباريات 2",results:"النتائج",teams:"الفرق",competitions:"كل المسابقات",register:"التسجيل",register2:"التسجيل 2",edit:"فريقي",rules:"القواعد",competition:"المسابقة",poolPoints:"النقاط",admin:"الإدارة"},
    matches2Tab:{
      selectCompetition:"المسابقة",
      noCompetitionsList:"لا توجد مسابقات متاحة.",
      needCompetition:"اختر مسابقة أولاً (كل المسابقات أو التسجيل).",
      empty:"لا توجد مباريات مرتبطة بهذه المجموعة بعد.",
      loadError:"تعذر التحميل.",
      noKickoffYet:"الموعد غير محدد",
      noGroupTeams:"لا توجد أسماء فرق لمرحلة المجموعات في البيانات بعد.",
      fromMappings:"من جدول المجموعة",
      competitionScheduleNote:"التوقيت يتبع المنطقة الزمنية الرسمية لهذه المسابقة (وليست منطقة ملفك).",
      noPoolStartDate:"لا توجد بعد تاريخ بداية لهذه المجموعة — يمكن للمنظم تعيينه عند التعديل.",
      viewStatistics:"عرض الإحصائيات",
    },
    countdownTo:"العد التنازلي لكأس العالم", days:"أيام",hours:"ساعات",minutes:"دقائق",seconds:"ثوان", started:"كأس العالم قد بدأ!",
    matchSchedule:"جدول المباريات",groups:"المجموعات",knockout:"الأدوار الإقصائية",
    r16:"دور الـ16",qr:"ربع النهائي",qf:"ربع النهائي",sf:"نصف النهائي",final:"النهائي",thirdp:"المركز الثالث", pts:"نقاط",
    noParticipants:"لا يوجد مشاركون بعد", register1:"التسجيل – الخطوة 1",register2:"التسجيل – الخطوة 2",
    name:"اسمك",teamName:"اسم الفريق",email:"البريد",system:"النظام",
    next:"التالي",back:"رجوع",submit:"إرسال الفريق",
    pickPlayers:"لاعب واحد لكل مركز من دولة — كل دولة مرة واحدة فقط لكل فريق", selectCountry:"اختر دولة", countryTaken:"الدولة مأخوذة",
    deadlinePassed:"انتهى الموعد النهائي (10 يونيو 2026).", deadlineBefore:"الموعد النهائي:",
    successReg:"تم تسجيل فريقك! 🎉",
    adminLogin:"دخول الإدارة",password:"كلمة المرور",login:"دخول",wrongPw:"كلمة مرور خاطئة",
    adminPanel:"إدارة النقاط",pointsManagement:"إدارة النقاط",poolPointsHint:"عدّل النقاط والتشكيلات للفرق في مسابقتك. الموعد النهائي العام للموقع يضبطه المشرف الأعلى من تبويب الإدارة.",poolPointsSelectPool:"مسابقتك",exportExcel:"تصدير Excel",logout:"خروج",save:"حفظ",saved:"تم الحفظ",
    noTeamsYet:"لا توجد فرق مسجلة بعد",
    pos:{keeper:"حارس",def:"مدافع",mid:"وسط",att:"مهاجم",coach:"مدرب"},
    resultsPage:"النتائج قريباً",
    timezoneInfo:"التوقيت في المنطقة:",changeTz:"تغيير المنطقة",groupLabel:"مجموعة",playerNamePlaceholder:"اسم اللاعب",fillPlayerNames:"املأ جميع الأسماء",searchPlaceholder:"ابحث عن فريق...",coachNamePlaceholder:"اسم المدرب (مثلاً رونالد كومان)",fillCoachName:"أدخل اسم المدرب",duplicateEmail:"هذا البريد مسجل بالفعل. فريق واحد لكل بريد.",knockoutInfo:"ستظهر مباريات الأدوار الإقصائية بعد انتهاء دور المجموعات.",tbd:"يُحدد لاحقاً",unsaved:"غير محفوظ",savingAutosave:"جارِ الحفظ…",deadlineConfig:"تعيين الموعد النهائي",deadlineDateLabel:"التاريخ والوقت",deadlineDisplayLabel:"النص المعروض",saveDeadline:"حفظ الموعد",confirmLogout:"هل أنت متأكد أنك تريد تسجيل الخروج من لوحة الإدارة؟",cancel:"إلغاء",settings:"الإعدادات",themeLabel:"السمة",darkTheme:"داكن",lightTheme:"فاتح",languageLabel:"اللغة",timezoneLabel:"المنطقة الزمنية",adminLoggedIn:"مسجل كمسؤول",changeInSettings:"غيّر في الإعدادات ⚙️",edit:"تعديل",editTeam:"تعديل الفريق",teamName:"اسم الفريق",userName:"الاسم",system:"النظام",fillRequired:"املأ جميع الحقول المطلوبة",choosePlayer:"اختر لاعباً",chooseCoach:"اختر مدرباً",playerNameManual:"الاسم (يدوياً)",rulesContent:{title:"قواعد اللعبة",intro:"مرحباً بك في توقعات كأس العالم 2026! اقرأ كيف تعمل اللعبة وكيف تكسب النقاط.",howTitle:"كيف تعمل؟",how1:"سجّل قبل الموعد النهائي.",how2:"اختر تشكيلة (4-3-3 أو 4-4-2 أو 3-4-3).",how3:"اختر دولة لكل مركز. كل دولة مرة واحدة فقط لكل شخص.",how4:"أدخل اسم المدرب.",how5:"خلال البطولة تكسب نقاطاً بناءً على أداء الدول واللاعبين.",how6:"من يحصل على أكبر عدد من النقاط يفوز!",deadlineTitle:"الموعد النهائي للتسجيل",deadlineText:"التسجيل متاح حتى:",deadlineNote:"بعد ذلك لا يمكن تعديل الفريق.",pointsTitle:"نظام النقاط",pointsIntro:"النقاط تختلف حسب المركز. المهاجمون يحصلون على نقاط أكثر للأهداف.",eventCol:"الحدث",evWin:"مباراة فائزة (الدولة)",evDraw:"تعادل (الدولة)",evGoal:"هدف",evAssist:"تمريرة حاسمة",evClean:"شباك نظيفة",evPenalty:"تصدي ركلة جزاء",evOg:"هدف عكسي",evYellow:"بطاقة صفراء",ev2Yellow:"صفراوان = حمراء",evRed:"بطاقة حمراء مباشرة",evSub:"تبديل ناجح (هدف بعد التبديل)",evChampion:"بطل العالم",rulesTitle:"قواعد مهمة",rule1:"التسجيل ببريد واحد — فريق واحد لكل شخص.",rule2:"داخل فريقك كل دولة مرة واحدة فقط.",rule3:"يمكن للآخرين اختيار نفس الدولة.",rule4:"بعد الموعد النهائي لا يمكن تعديل الفريق.",rule5:"يتم تحديث النقاط باستمرار من قِبل المسؤول.",rule6:"في حالة التعادل يفوز من لديه أهداف مهاجمين أكثر.",prizesTitle:"الجوائز والاتصال",prizesText:"يعلن المنظم عن الجوائز. الاشتراكات والمدفوعات تتم بشكل منفصل.",contactText:"هل لديك أسئلة؟ تواصل مع منظم البطولة.",privacyTitle:"الخصوصية",privacyText:"يُستخدم بريدك الإلكتروني فقط لمنع التسجيلات المكررة.",captainTitle:"القائد",captainText:"تختار لاعباً كقائد. إذا أصبح بلده بطلاً، يحصل على نقاط البطولة مثل باقي لاعبيك من نفس البلد.",captainNote:"يظهر قائدك بشارة برتقالية. اختر بحكمة!",exampleTitle:"فريق مثال (4-3-3)",exampleIntro:"مثال صالح: كل بلد مرة واحدة، القائد بالشارة.",exampleNote:"استخدام الأرجنتين مرتين خطأ — غير مسموح.",mistakesTitle:"الأخطاء الشائعة"}
  }
};

